name: Run Playwright Script and Upload Artifacts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and browsers
        run: |
          pip install playwright
          playwright install --with-deps

      - name: Run Python Playwright script
        run: python 4.py

      - name: Upload downloaded files
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-report
          path: downloads/
